import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from datetime import datetime

def generate_research_pdf_report(metrics_data: dict, researcher_id: str, provenance_hash: str, output_path: str = "research_report.pdf"):
    """Generates a structured, enterprise-grade research report in PDF format."""
    doc = SimpleDocTemplate(output_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []

    # Title Banner
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=12
    )
    story.append(Paragraph("🧬 Executive Research Analysis & Provenance Report", title_style))
    story.append(Paragraph(f"<b>Generated By:</b> {researcher_id} | <b>Date:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", styles['Normal']))
    story.append(Spacer(1, 15))

    # Metric Table Summary
    table_data = [
        ["Analytical Parameter", "Observed Value"],
        ["Sequence Length", f"{metrics_data.get('length', 'N/A')} bp"],
        ["GC Content Ratio", f"{metrics_data.get('gc_content', 'N/A')}%"],
        ["AT Content Ratio", f"{metrics_data.get('at_content', 'N/A')}%"],
        ["Total Codons Parsed", str(metrics_data.get('total_codons', 'N/A'))],
    ]

    t = Table(table_data, colWidths=[240, 240])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8FAFC')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
    ]))
    story.append(t)
    story.append(Spacer(1, 20))

    # Provenance Hash Verification Section
    story.append(Paragraph("<b>SHA-256 Provenance Audit Stamp:</b>", styles['Heading3']))
    hash_style = ParagraphStyle('HashText', parent=styles['Code'], fontSize=8, textColor=colors.HexColor('#475569'))
    story.append(Paragraph(provenance_hash, hash_style))
    story.append(Spacer(1, 15))

    story.append(Paragraph("<i>This document confirms compliance with FAIR data principles and cryptographically stamped execution logs.</i>", styles['Italic']))

    doc.build(story)
    return output_path
