import streamlit as st
import sqlite3
import pandas as pd
from datetime import datetime

def render_report_exporter():
    """
    Renders an audit report generator that packages active session logs and metrics into a downloadable HTML document.
    """
    st.subheader(" Enterprise Session Audit Report Generator")
    st.caption("Export a certified executive activity and database event report for documentation.")

    if st.button("Generate Certified HTML Audit Report"):
        try:
            conn = sqlite3.connect("chrishem_engine.db")
            df_logs = pd.read_sql_query("SELECT * FROM system_logs ORDER BY id DESC LIMIT 50", conn)
            df_sessions = pd.read_sql_query("SELECT * FROM user_sessions", conn)
            conn.close()

            current_user = st.session_state.get('user', 'Authorized User')
            report_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

            html_content = f\"\"\"
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <title>CHRISHEM Engine Audit Report</title>
                <style>
                    body {{ font-family: Arial, sans-serif; background: #f4f6f9; color: #333; padding: 20px; }}
                    .container {{ max-width: 900px; margin: auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
                    h1 {{ color: #1e3a8a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }}
                    h3 {{ color: #374151; margin-top: 25px; }}
                    table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
                    th, td {{ border: 1px solid #e5e7eb; padding: 10px; text-align: left; font-size: 14px; }}
                    th {{ background: #1e3a8a; color: white; }}
                    tr:nth-child(even {{ background: #f9fafb; }})
                    .meta {{ background: #e0f2fe; padding: 15px; border-radius: 6px; margin-bottom: 20px; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>? CHRISHEM Enterprise Intelligence Engine</h1>
                    <div class="meta">
                        <p><strong>Generated By:</strong> {current_user}</p>
                        <p><strong>Timestamp:</strong> {report_time}</p>
                        <p><strong>Security Status:</strong> AES-256 Encrypted & WAF Active</p>
                    </div>
                    
                    <h3> Active User Sessions</h3>
                    {df_sessions.to_html(index=False, classes='table')}

                    <h3> Recent System Audit Logs</h3>
                    {df_logs.to_html(index=False, classes='table')}
                </div>
            </body>
            </html>
            \"\"\"

            st.download_button(
                label=" Download Certified HTML Report",
                data=html_content,
                file_name=f"chrishem_audit_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html",
                mime="text/html"
            )
            st.toast("Audit report generated successfully!", icon="")
        except Exception as e:
            st.error(f"Failed to generate report: {str(e)}")
