"""Generate StealthHumanizer and Analytics for audit_portal.py"""
f = open('d:/notion-live-analyzer/modules/audit_portal.py', 'a', encoding='utf-8')
w = f.write

w('\n# ==== STEALTH HUMANIZER ====\n')
w('class StealthHumanizer:\n')
w('    """Comprehensive AI-trace erasing humanizer."""\n')
w('    def __init__(self):\n')
w('        self.contractions = {\n')
w('            "cannot":"can\'t","will not":"won\'t","do not":"don\'t",\n')
w('            "does not":"doesn\'t","is not":"isn\'t","are not":"aren\'t",\n')
w('            "has not":"hasn\'t","have not":"haven\'t","it is":"it\'s",\n')
w('            "that is":"that\'s","there is":"there\'s","I am":"I\'m",\n')
w('            "we are":"we\'re","they are":"they\'re","would not":"wouldn\'t",\n')
w('            "should not":"shouldn\'t","could not":"couldn\'t","did not":"didn\'t"\n')
w('        }\n')
w('        self.hedging = ["appears","seems","suggests","indicates","likely",\n')
w('            "perhaps","may","might","could","potentially","plausibly"]\n')
w('        self.confident = ["demonstrates","confirms","establishes","proves",\n')
w('            "shows","reveals","indicates","highlights"]\n')
w('        self.starters = ["Notably,","Importantly,","Interestingly,",\n')
w('            "Furthermore,","Moreover,","In addition,","However,",\n')
w('            "Nevertheless,","Alternatively,","Specifically,",\n')
w('            "To illustrate,","As expected,","Strikingly,","Consequently,"]\n')
w('        self.transitions = ["Furthermore","In addition","Moreover",\n')
w('            "However","Nevertheless","On the other hand","Specifically",\n')
w('            "For instance","As a result","Consequently","Therefore",\n')
w('            "Thus","Hence","Subsequently","Meanwhile","Overall","Additionally"]\n')
w('        self.academic_verbs = {\n')
w('            "use":["utilize","employ","leverage","apply"],\n')
w('            "show":["demonstrate","reveal","illustrate","depict"],\n')
w('            "get":["obtain","acquire","derive","attain"],\n')
w('            "make":["construct","generate","produce","formulate"],\n')
w('            "change":["modify","transform","adjust","refine"],\n')
w('            "help":["facilitate","enable","support","assist"],\n')
w('            "find":["identify","detect","locate","determine"],\n')
w('            "give":["provide","supply","yield","offer"],\n')
w('            "need":["require","necessitate","demand"],\n')
w('            "look":["examine","investigate","explore","analyze"]\n')
w('        }\n')

w('    def _pnoise(self, text, intensity=0.3):\n')
w('        import random\n')
w('        words = text.split()\n')
w('        n = max(1,int(len(words)*intensity*0.08))\n')
w('        for _ in range(n):\n')
w('            i = random.randint(0,len(words)-1)\n')
w('            if len(words[i])>3 and random.random()<0.4:\n')
w('                words[i] = words[i][:-1]+chr(random.choice([97,101,105,111,117]))\n')
w('        return " ".join(words)\n')

w('    def _vburst(self, text, tb=0.6):\n')
w('        import random\n')
w('        sents = [s.strip() for s in text.replace("?",".").replace("!",".").split(".") if s.strip()]\n')
w('        if len(sents) < 5: return text\n')
w('        res = []\n')
w('        for s in sents:\n')
w('            nw = len(s.split())\n')
w('            if nw < 5 and random.random()<0.3:\n')
w('                res.append(s+" "+random.choice(self.starters)+" "+s.lower())\n')
w('            elif nw > 20 and random.random()<0.3:\n')
w('                res.append(s[:len(s)//2]+"."); res.append(s[len(s)//2:].strip()+".")\n')
w('            else: res.append(s)\n')
w('        return ". ".join(res)+"."\n')

w('    def _ahedge(self, text):\n')
w('        import re, random\n')
w('        for wd in self.confident:\n')
w('            if wd in text.lower() and random.random()<0.35:\n')
w('                text = re.sub(r"\\b"+wd+r"\\b", random.choice(self.hedging), text, flags=re.I)\n')
w('        return text\n')

w('    def _dstarters(self, text):\n')
w('        import random\n')
w('        sents = [s.strip() for s in text.replace("?",".").replace("!",".").split(".") if s.strip()]\n')
w('        if len(sents) < 3: return text\n')
w('        res = []\n')
w('        for i,s in enumerate(sents):\n')
w('            if i>0 and i%2==0 and random.random()<0.4:\n')
w('                res.append(random.choice(self.starters)+" "+s[0].lower()+s[1:])\n')
w('            else: res.append(s)\n')
w('        return ". ".join(res)+"."\n')

w('    def _contract(self, text):\n')
w('        import re, random\n')
w('        for full,cont in self.contractions.items():\n')
w('            if random.random()<0.5:\n')
w('                text = re.sub(r"\\b"+full+r"\\b", cont, text, flags=re.I)\n')
w('        return text\n')

w('    def _upgrade_vocab(self, text):\n')
w('        import re, random\n')
w('        for simple,upgrades in self.academic_verbs.items():\n')
w('            if random.random()<0.4:\n')
w('                text = re.sub(r"\\b"+simple+r"(\\w*)\\b", random.choice(upgrades), text, flags=re.I)\n')
w('        return text\n')

w('    def _transitions(self, text):\n')
w('        import random\n')
w('        sents = [s.strip() for s in text.split(".") if s.strip()]\n')
w('        if len(sents) < 4: return text\n')
w('        res = []\n')
w('        for i,s in enumerate(sents):\n')
w('            if 0<i<len(sents)-1 and random.random()<0.25:\n')
w('                res.append(random.choice(self.transitions)+", "+s[0].lower()+s[1:])\n')
w('            else: res.append(s)\n')
w('        return ". ".join(res)+"."\n')

w('    def _commentary(self, text):\n')
w('        import random\n')
w('        cmts = ["it is worth noting that ","this is particularly relevant because ",\n')
w('            "it should be emphasized that ","this finding aligns with the expectation that ",\n')
w('            "one might reasonably conclude that ","this observation suggests that ",\n')
w('            "importantly, this indicates that ","this result underscores the fact that "]\n')
w('        sents = [s.strip() for s in text.split(".") if s.strip()]\n')
w('        if len(sents) < 4: return text\n')
w('        res = []\n')
w('        for i,s in enumerate(sents):\n')
w('            if 0<i<len(sents)-1 and random.random()<0.15:\n')
w('                res.append(random.choice(cmts)+s[0].lower()+s[1:])\n')
w('            else: res.append(s)\n')
w('        return ". ".join(res)+"."\n')

w('    def full_humanize(self, text, burstiness=0.6, perplexity=0.3):\n')
w('        """Apply all humanization layers to remove AI traces."""\n')
w('        t = self._contract(text)\n')
w('        t = self._upgrade_vocab(t)\n')
w('        t = self._ahedge(t)\n')
w('        t = self._dstarters(t)\n')
w('        t = self._transitions(t)\n')
w('        t = self._commentary(t)\n')
w('        t = self._vburst(t, burstiness)\n')
w('        t = self._pnoise(t, perplexity)\n')
w('        return t\n')

w('    def compute_stats(self, text):\n')
w('        words = text.split(); chars = len(text)\n')
w('        sents = [s for s in text.replace("?",".").replace("!",".").split(".") if s.strip()]\n')
w('        wl = [len(w) for w in words if w]\n')
w('        burst = round(statistics.stdev([len(s.split()) for s in sents]) if len(sents)>1 else 0, 2)\n')
w('        avg_w = round(statistics.mean([len(s.split()) for s in sents]) if sents else 0, 1)\n')
w('        pplex = round(len(set(w.lower() for w in words))/len(words)*100 if words else 0, 1)\n')
w('        return {"words":len(words),"chars":chars,"sentences":len(sents),\n')
w('            "burstiness":burst,"avg_sentence_len":avg_w,\n')
w('            "perplexity":pplex,\n')
w('            "avg_word_len":round(statistics.mean(wl),1) if wl else 0}\n')

w('\n# ==== ANALYTICS & TRACE-BACK ENGINE ====\n')
w('class CHRISHEMAnalyticsEngine:\n')
w('    """Plotly-based trace-back graphs, blockchain visualization, risk dashboards."""\n')
w('    def __init__(self, db=DB_PATH):\n')
w('        self.db = Path(db)\n')
w('    def _conn(self):\n')
w('        c = sqlite3.connect(str(self.db))\n')
w('        c.row_factory = sqlite3.Row; return c\n')

w('    def blockchain_chain_graph(self, pid=0):\n')
w('        """Visualize the blockchain as a directed graph (Plotly)."""\n')
w('        from modules.audit_engine import get_audit_orchestrator\n')
w('        try:\n')
w('            orch = get_audit_orchestrator(pid)\n')
w('            chain = orch.ledger.get_chain(pid) if hasattr(orch.ledger, "get_chain") else []\n')
w('            if not chain or len(chain) < 2:\n')
w('                return px.scatter(title="Blockchain - insufficient blocks")\n')
w('            df = pd.DataFrame(chain)\n')
w('            df["index"] = range(len(df))\n')
w('            df["short_hash"] = df["hash"].astype(str).str[:8]\n')
w('            df["prev_short"] = df["previous_hash"].astype(str).str[:8]\n')
w('            fig = make_subplots(specs=[[{"secondary_y":False}]])\n')
w('            fig.add_trace(go.Scatter(\n')
w('                x=df["index"], y=[1]*len(df),\n')
w('                mode="markers+text", marker=dict(size=20,\n')
w('                    color=df["index"], colorscale="Viridis", showscale=True),\n')
w('                text=df["short_hash"], textposition="top center",\n')
w('                hovertemplate="Block %{x}<br>Hash: %{text}<br>Prev: %{customdata}",\n')
w('                customdata=df["prev_short"], name="Blocks"\n')
w('            ))\n')
w('            for i in range(1, len(df)):\n')
w('                fig.add_annotation(x=df["index"].iloc[i-1], y=1,\n')
w('                    ax=df["index"].iloc[i], ay=1,\n')
w('                    axref="x", ayref="y", xref="x", yref="y",\n')
w('                    showarrow=True, arrowhead=2, arrowsize=1.5, arrowwidth=2,\n')
w('                    arrowcolor="#636efa")\n')
w('            fig.update_layout(title=f"Blockchain Ledger - {len(df)} Blocks",\n')
w('                xaxis_title="Block Index", yaxis=dict(showticklabels=False, showgrid=False),\n')
w('                height=300, showlegend=False, plot_bgcolor="rgba(0,0,0,0)")\n')
w('            return fig\n')
w('        except Exception as e:\n')
w('            return px.scatter(title=f"Chain graph error: {e}")\n')

w('    def submission_trace_graph(self, pid=0):\n')
w('        """Trace-back timeline of submissions with status flow."""\n')
w('        try:\n')
w('            subs = CHRISHEMSubmissionSystem(self.db).get(pid)\n')
w('            if not subs: return px.scatter(title="No submissions yet")\n')
w('            df = pd.DataFrame(subs)\n')
w('            df["submitted_at"] = pd.to_datetime(df["submitted_at"], unit="s")\n')
w('            df["reviewed_at"] = pd.to_datetime(df["reviewed_at"], unit="s") if "reviewed_at" in df else None\n')
w('            status_map = {"submitted":0,"reviewed":1,"returned":2}\n')
w('            df["status_code"] = df["status"].map(status_map).fillna(0)\n')
w('            fig = go.Figure()\n')
w('            for _,row in df.iterrows():\n')
w('                color = {"submitted":"#636efa","reviewed":"#00cc96","returned":"#ef553b"}\n')
w('                c = color.get(row["status"],"#636efa")\n')
w('                fig.add_trace(go.Scatter(\n')
w('                    x=[row["submitted_at"]]*2 if row["status"]=="submitted" else [row["submitted_at"],row.get("reviewed_at",row["submitted_at"])],\n')
w('                    y=[0,row["status_code"]],\n')
w('                    mode="lines+markers", name=row.get("title","Submission"),\n')
w('                    line=dict(color=c, width=2),\n')
w('                    marker=dict(size=[8,12], color=c, symbol=["circle","diamond"]),\n')
w('                    hovertemplate=f"<b>{row.get("title","")}</b><br>Student: {row.get("student_name","")}<br>Status: {row["status"]}<br>Score: {row.get("professor_score","N/A")}",\n')
w('                    showlegend=False\n')
w('                ))\n')
w('            fig.update_layout(title="Submission Trace-Back Timeline",\n')
w('                xaxis_title="Date", yaxis=dict(tickmode="array",\n')
w('                    tickvals=[0,1,2], ticktext=["Submitted","Reviewed","Returned"]),\n')
w('                height=400, hovermode="closest",\n')
w('                plot_bgcolor="rgba(0,0,0,0)")\n')
w('            return fig\n')
w('        except Exception as e:\n')
w('            return px.scatter(title=f"Trace error: {e}")\n')

w('    def risk_heatmap(self, pid=0):\n')
w('        """Risk assessment heatmap across submissions."""\n')
w('        try:\n')
w('            subs = CHRISHEMSubmissionSystem(self.db).get(pid)\n')
w('            if not subs: return px.imshow([[0]], text_auto=True, title="No data")\n')
w('            df = pd.DataFrame(subs)\n')
w('            pivot = df.pivot_table(index="student_name", columns="status",\n')
w('                aggfunc="size", fill_value=0)\n')
w('            for s in ["submitted","reviewed","returned"]:\n')
w('                if s not in pivot.columns: pivot[s] = 0\n')
w('            pivot = pivot[["submitted","reviewed","returned"]]\n')
w('            fig = px.imshow(pivot, text_auto=True, aspect="auto",\n')
w('                color_continuous_scale="RdYlGn_r",\n')
w('                title="Submission Status Heatmap", height=250+25*len(pivot))\n')
w('            fig.update_layout(plot_bgcolor="rgba(0,0,0,0)")\n')
w('            return fig\n')
w('        except Exception as e:\n')
w('            return px.imshow([[0]], title=f"Error: {e}")\n')

w('    def grade_distribution(self, pid=0):\n')
w('        """Grade distribution bar chart."""\n')
w('        try:\n')
w('            subs = CHRISHEMSubmissionSystem(self.db).get(pid, status="reviewed")\n')
w('            if not subs: return px.bar(title="No graded submissions")\n')
w('            df = pd.DataFrame(subs)\n')
w('            if "professor_grade" not in df.columns: return px.bar(title="No grades")\n')
w('            grades = df["professor_grade"].value_counts().reset_index()\n')
w('            grades.columns = ["Grade","Count"]\n')
w('            fig = px.bar(grades, x="Grade", y="Count", text_auto=True,\n')
w('                title="Grade Distribution",\n')
w('                color="Grade", color_discrete_map={\n')
w('                    "A":"#00cc96","B":"#636efa","C":"#ffa15a","D":"#ef553b","F":"#ab63fa"},\n')
w('                height=350)\n')
w('            fig.update_layout(plot_bgcolor="rgba(0,0,0,0)", showlegend=False)\n')
w('            return fig\n')
w('        except Exception as e:\n')
w('            return px.bar(title=f"Error: {e}")\n')

w('    def score_trend(self, pid=0):\n')
w('        """Score trend over submissions timeline."""\n')
w('        try:\n')
w('            subs = CHRISHEMSubmissionSystem(self.db).get(pid, status="reviewed")\n')
w('            if not subs: return px.line(title="No reviewed submissions")\n')
w('            df = pd.DataFrame(subs)\n')
w('            df["reviewed_at"] = pd.to_datetime(df["reviewed_at"], unit="s")\n')
w('            df = df.sort_values("reviewed_at")\n')
w('            fig = px.line(df, x="reviewed_at", y="professor_score",\n')
w('                title="Score Trend Over Time",\n')
w('                markers=True, text="student_name",\n')
w('                labels={"professor_score":"Score","reviewed_at":"Date"},\n')
w('                height=350)\n')
w('            fig.add_hline(y=df["professor_score"].mean(),\n')
w('                line_dash="dash", line_color="gray",\n')
w('                annotation_text=f"Avg: {df['professor_score'].mean():.1f}")\n')
w('            fig.update_traces(textposition="top center")\n')
w('            fig.update_layout(plot_bgcolor="rgba(0,0,0,0)")\n')
w('            return fig\n')
w('        except Exception as e:\n')
w('            return px.line(title=f"Error: {e}")\n')

w('    def student_activity_gantt(self, pid=0):\n')
w('        """Student submission activity as Gantt-like chart."""\n')
w('        try:\n')
w('            subs = CHRISHEMSubmissionSystem(self.db).get(pid)\n')
w('            if not subs: return px.timeline(title="No activity")\n')
w('            df = pd.DataFrame(subs)\n')
w('            df["start"] = pd.to_datetime(df["submitted_at"], unit="s")\n')
w('            df["end"] = pd.to_datetime(df.get("reviewed_at",df["submitted_at"]), unit="s")\n')
w('            df["duration_h"] = (df["end"]-df["start"]).dt.total_seconds()/3600\n')
w('            fig = px.timeline(df, x_start="start", x_end="end",\n')
w('                y="student_name", color="status",\n')
w('                title="Student Activity Timeline",\n')
w('                color_discrete_map={"submitted":"#636efa","reviewed":"#00cc96","returned":"#ef553b"},\n')
w('                height=200+30*len(df))\n')
w('            fig.update_layout(plot_bgcolor="rgba(0,0,0,0)",\n')
w('                xaxis_title="Date", yaxis_title="Student")\n')
w('            return fig\n')
w('        except Exception as e:\n')
w('            return px.timeline(title=f"Error: {e}")\n')

w('    def analytics_dashboard(self, pid=0):\n')
w('        """Full analytics dashboard with multiple plots."""\n')
w('        try:\n')
w('            subs = CHRISHEMSubmissionSystem(self.db).get(pid)\n')
w('            if not subs:\n')
w('                fig = go.Figure()\n')
w('                fig.add_annotation(text="No data available", x=0.5, y=0.5, showarrow=False)\n')
w('                return fig\n')
w('            df = pd.DataFrame(subs)\n')
w('            fig = make_subplots(rows=2, cols=2,\n')
w('                subplot_titles=("Status Distribution","Scores","Submissions Over Time","Activity"),\n')
w('                specs=[[{"type":"pie"},{"type":"bar"}],[{"type":"scatter"},{"type":"bar"}]])\n')
w('            # Pie - status\n')
w('            status_counts = df["status"].value_counts()\n')
w('            fig.add_trace(go.Pie(labels=status_counts.index, values=status_counts.values,\n')
w('                marker=dict(colors=["#636efa","#00cc96","#ef553b"])), row=1, col=1)\n')
w('            # Bar - scores\n')
w('            if "professor_score" in df.columns:\n')
w('                scored = df[df["professor_score"].notna()]\n')
w('                if len(scored):\n')
w('                    fig.add_trace(go.Bar(x=scored["student_name"], y=scored["professor_score"],\n')
w('                        marker_color="#636efa"), row=1, col=2)\n')
w('            # Scatter - submissions over time\n')
w('            df["sub_date"] = pd.to_datetime(df["submitted_at"], unit="s")\n')
w('            daily = df.groupby(df["sub_date"].dt.date).size().reset_index(name="count")\n')
w('            fig.add_trace(go.Scatter(x=daily["sub_date"], y=daily["count"],\n')
w('                mode="lines+markers", marker_color="#00cc96"), row=2, col=1)\n')
w('            # Bar - student activity\n')
w('            student_counts = df["student_name"].value_counts()\n')
w('            fig.add_trace(go.Bar(x=student_counts.index, y=student_counts.values,\n')
w('                marker_color="#ffa15a"), row=2, col=2)\n')
w('            fig.update_layout(height=600, title_text="Analytics Dashboard",\n')
w('                showlegend=False, plot_bgcolor="rgba(0,0,0,0)")\n')
w('            return fig\n')
w('        except Exception as e:\n')
w('            fig = go.Figure()\n')
w('            fig.add_annotation(text=f"Error: {e}", x=0.5, y=0.5, showarrow=False)\n')
w('            return fig\n')

w('\n# ==== PORTAL UI ====\n')
w('def render_student_portal():\n')
w('    """Student submission tab UI."""\n')
w('    st.subheader("Student Submission Portal")\n')
w('    st.info("Submit your work via Fernet-encrypted channel.")\n')
w('    sub = CHRISHEMSubmissionSystem()\n')
w('    tab1, tab2 = st.tabs(["New Submission","My Submissions"])\n')
w('    with tab1:\n')
w('        name = st.text_input("Your Name", key="sp_name")\n')
w('        email = st.text_input("Email (optional)", key="sp_email")\n')
w('        title = st.text_input("Submission Title", key="sp_title")\n')
w('        content = st.text_area("Your Work / Essay / Report", height=200, key="sp_content")\n')
w('        password = st.text_input("Encryption Password", type="password", value="CHRISHEM", key="sp_pwd")\n')
w('        if st.button("Encrypt & Submit", type="primary", use_container_width=True):\n')
w('            if name and title and content:\n')
w('                res = sub.submit(0, name, title, content, password, email=email)\n')
w('                if res.get("id"):\n')
w('                    st.success(res["msg"])\n')
w('                    st.code(f"Blockchain Hash: {res['hash'][:16]}...", language="text")\n')
w('            else: st.warning("Name, Title, and Content required.")\n')
w('    with tab2:\n')
w('        sname = st.text_input("Enter your name to view submissions", key="sp_view_name")\n')
w('        if sname:\n')
w('            subs = sub.get(name=sname)\n')
w('            if subs:\n')
w('                stats = sub.student_stats(0, sname)\n')
w('                c1,c2,c3,c4 = st.columns(4)\n')
w('                c1.metric("Total", stats["total"])\n')
w('                c2.metric("Reviewed", stats["reviewed"])\n')
w('                c3.metric("Pending", stats["pending"])\n')
w('                c4.metric("Avg Score", stats["avg_score"])\n')
w('                pw = st.text_input("Decryption Password", type="password", key="sp_dec_pwd")\n')
w('                for s in subs:\n')
w('                    with st.expander(f"{s['title']} - {s['status'].upper()} ({s.get('professor_grade','?')})"):\n')
w('                        st.write(f"Submitted: {datetime.fromtimestamp(s['submitted_at']).strftime('%Y-%m-%d %H:%M')}")\n')
w('                        st.write(f"Status: {s['status']}")\n')
w('                        if s.get("professor_score"):\n')
w('                            st.metric("Score", s["professor_score"])\n')
w('                        if s.get("professor_grade"):\n')
w('                            st.write(f"Grade: {s['professor_grade']}")\n')
w('                        if pw and st.button(f"Decrypt #{s['id']}", key=f"dec_{s['id']}"):\n')
w('                            dec = sub.decrypt(s["id"], pw)\n')
w('                            if dec and not dec.startswith("[Decrypt"):\n')
w('                                st.text_area("Decrypted Content", dec, height=150)\n')
w('                            else: st.error(dec)\n')
w('                        if s.get("professor_feedback") and pw:\n')
w('                            try:\n')
w('                                fb = decrypt_text(s["professor_feedback"], pw)\n')
w('                                if not fb.startswith("[Decrypt"):\n')
w('                                    st.info(f"Feedback: {fb}")\n')
w('                            except: pass\n')
w('            else: st.info("No submissions found for this name.")\n')

w('def render_professor_dashboard():\n')
w('    """Professor review and grading dashboard with graphs."""\n')
w('    st.subheader("Professor Dashboard")\n')
w('    sub = CHRISHEMSubmissionSystem()\n')
w('    analytics = CHRISHEMAnalyticsEngine()\n')
w('    subs = sub.get()\n')
w('    pending = [s for s in subs if s["status"]=="submitted"]\n')
w('    c1,c2,c3 = st.columns(3)\n')
w('    c1.metric("Total Submissions", len(subs))\n')
w('    c2.metric("Pending Review", len(pending))\n')
w('    c3.metric("Reviewed", len([s for s in subs if s["status"]=="reviewed"]))\n')

w('    # Show graphs\n')
w('    g1,g2 = st.columns(2)\n')
w('    with g1:\n')
w('        fig1 = analytics.submission_trace_graph()\n')
w('        if fig1: st.plotly_chart(fig1, use_container_width=True)\n')
w('    with g2:\n')
w('        fig2 = analytics.risk_heatmap()\n')
w('        if fig2: st.plotly_chart(fig2, use_container_width=True)\n')
w('    g3,g4 = st.columns(2)\n')
w('    with g3:\n')
w('        fig3 = analytics.grade_distribution()\n')
w('        if fig3: st.plotly_chart(fig3, use_container_width=True)\n')
w('    with g4:\n')
w('        fig4 = analytics.score_trend()\n')
w('        if fig4: st.plotly_chart(fig4, use_container_width=True)\n')

w('    # Review pending\n')
w('    if pending:\n')
w('        st.subheader("Pending Reviews")\n')
w('        pw = st.text_input("Professor Password", type="password", key="prof_pwd")\n')
w('        for s in pending:\n')
w('            with st.expander(f"{s['title']} - {s['student_name']}"):\n')
w('                st.write(f"Submitted: {datetime.fromtimestamp(s['submitted_at']).strftime('%Y-%m-%d %H:%M')}")\n')
w('                if pw:\n')
w('                    dec = sub.decrypt(s["id"], pw)\n')
w('                    if dec and not dec.startswith("[Decrypt"):\n')
w('                        st.text_area("Content", dec, height=200, key=f"prof_{s['id']}")\n')
w('                col1,col2 = st.columns(2)\n')
w('                with col1:\n')
w('                    grade = st.selectbox(f"Grade #{s['id']}", ["A","B","C","D","F"], key=f"g_{s['id']}")\n')
w('                    score = st.slider(f"Score #{s['id']}", 0, 100, 75, key=f"s_{s['id']}")\n')
w('                with col2:\n')
w('                    fb = st.text_area(f"Feedback #{s['id']}", key=f"fb_{s['id']}")\n')
w('                c1,c2 = st.columns(2)\n')
w('                with c1:\n')
w('                    if st.button(f"Approve and Grade #{s['id']}", key=f"app_{s['id']}"):\n')
w('                        if pw:\n')
w('                            sub.review(s["id"], grade, score, fb, pw)\n')
w('                            st.success("Reviewed!"); st.rerun()\n')
w('                with c2:\n')
w('                    if st.button(f"Return for Revision #{s['id']}", key=f"ret_{s['id']}"):\n')
w('                        if pw:\n')
w('                            sub.return_revision(s["id"], fb, pw)\n')
w('                            st.success("Returned!"); st.rerun()\n')

w('def render_chrishem_analytics():\n')
w('    """CHRISHEM Analytics tab with trace-backs and blockchain viz."""\n')
w('    st.subheader("CHRISHEM Analytics & Trace-Backs")\n')
w('    analytics = CHRISHEMAnalyticsEngine()\n')
w('    anal, trace, chain = st.tabs(["Analytics Dashboard","Trace-Back Graph","Blockchain Explorer"])\n')
w('    with anal:\n')
w('        fig = analytics.analytics_dashboard()\n')
w('        st.plotly_chart(fig, use_container_width=True)\n')
w('    with trace:\n')
w('        fig = analytics.submission_trace_graph()\n')
w('        st.plotly_chart(fig, use_container_width=True)\n')
w('        col1,col2 = st.columns(2)\n')
w('        with col1:\n')
w('            fig2 = analytics.student_activity_gantt()\n')
w('            st.plotly_chart(fig2, use_container_width=True)\n')
w('        with col2:\n')
w('            fig3 = analytics.risk_heatmap()\n')
w('            st.plotly_chart(fig3, use_container_width=True)\n')
w('    with chain:\n')
w('        fig = analytics.blockchain_chain_graph()\n')
w('        st.plotly_chart(fig, use_container_width=True)\n')
w('        st.caption("Each block is cryptographically linked to the previous block via SHA-256 hash.")\n')
w('        st.caption("Tampering with any block breaks the chain - instantly detectable.")\n')

w('def render_stealth_humanizer():\n')
w('    """Stealth Humanizer tab for text anti-AI-detection."""\n')
w('    st.subheader("CHRISHEM Stealth Humanizer")\n')
w('    st.info("Comprehensively removes AI writing traces - burstiness, perplexity, hedging, contractions, vocabulary, transitions, and more.")\n')
w('    h = StealthHumanizer()\n')
w('    text = st.text_area("Paste AI-generated text to humanize:", height=200, key="humanizer_input")\n')
w('    b = st.slider("Burstiness (sentence length variation)", 0.0, 1.0, 0.6, 0.05, key="h_burst")\n')
w('    p = st.slider("Perplexity (vocabulary randomness)", 0.0, 1.0, 0.3, 0.05, key="h_pplex")\n')
w('    if text and st.button("Apply Humanization", type="primary", use_container_width=True):\n')
w('        with st.spinner("Humanizing..."):\n')
w('            orig_stats = h.compute_stats(text)\n')
w('            result = h.full_humanize(text, b, p)\n')
w('            new_stats = h.compute_stats(result)\n')
w('            c1,c2 = st.columns(2)\n')
w('            with c1:\n')
w('
f.close()
print(" StealthHumanizer done\)