"""Tests for Phase 152 continuity review lifecycle."""
from nema_agora.api_governance_drift_recovery_authorization_retention_registry_lifecycle_decision_history_registry_lifecycle_decision_continuity_phase147 import build_authorization_history_registry_decision_history_lifecycle_decision_continuity
from nema_agora.api_governance_drift_recovery_authorization_retention_registry_lifecycle_decision_history_registry_lifecycle_decision_continuity_monitor_phase149 import build_authorization_history_registry_decision_history_lifecycle_decision_continuity_monitor
from nema_agora.api_governance_drift_recovery_authorization_retention_registry_lifecycle_decision_history_registry_lifecycle_decision_continuity_review_phase150 import review_authorization_history_registry_decision_history_lifecycle_decision_continuity
from nema_agora.api_governance_drift_recovery_authorization_retention_registry_lifecycle_decision_history_registry_lifecycle_decision_continuity_review_reconciliation_phase151 import reconcile_authorization_history_registry_decision_history_lifecycle_decision_continuity_reviews
from nema_agora.api_governance_drift_recovery_authorization_retention_registry_lifecycle_decision_history_registry_lifecycle_decision_continuity_review_lifecycle_phase152 import evaluate_authorization_history_registry_decision_history_lifecycle_decision_continuity_review_lifecycle,validate_authorization_history_registry_decision_history_lifecycle_decision_continuity_review_lifecycle
def pair():
 s=build_authorization_history_registry_decision_history_lifecycle_decision_continuity([],captured_at="2026-10-04T09:00:00+00:00",sequence=1)
 m=build_authorization_history_registry_decision_history_lifecycle_decision_continuity_monitor([s],expected_count=1,observed_at="2026-10-04T10:00:00+00:00")
 r=review_authorization_history_registry_decision_history_lifecycle_decision_continuity(m,actor_id="reviewer",role="coordinator",outcome="ACKNOWLEDGED",reviewed_at="2026-10-04T11:00:00+00:00")
 rec=reconcile_authorization_history_registry_decision_history_lifecycle_decision_continuity_reviews([m],[r],expected_review_count=1)
 return r,rec
def test_healthy_acknowledged_lifecycle():
 r,_=pair(); x=evaluate_authorization_history_registry_decision_history_lifecycle_decision_continuity_review_lifecycle(r,evaluated_at="2026-10-04T12:00:00+00:00")
 assert x["state"]=="ACKNOWLEDGED"; assert validate_authorization_history_registry_decision_history_lifecycle_decision_continuity_review_lifecycle(x)==x
def test_execution_boundary():
 r,_=pair(); r=dict(r,execution_performed=True)
 from pytest import raises
 with raises(ValueError): evaluate_authorization_history_registry_decision_history_lifecycle_decision_continuity_review_lifecycle(r,evaluated_at="2026-10-04T12:00:00+00:00")
def test_reconciliation_binding_is_preserved():
 r,rec=pair()
 from nema_agora.api_governance_drift_recovery_authorization_retention_registry_lifecycle_decision_history_registry_lifecycle_decision_continuity_review_lifecycle_phase152 import build_authorization_history_registry_decision_history_lifecycle_decision_continuity_review_lifecycle
 x=build_authorization_history_registry_decision_history_lifecycle_decision_continuity_review_lifecycle(rec,[r],evaluated_at="2026-10-04T12:00:00+00:00")[0]
 assert x["review_fingerprint"]==r["review_fingerprint"]; assert x["monitor_fingerprint"]==r["monitor_fingerprint"]
